package com.agenda.omarche.agenda.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import java.io.Serializable;

/**
 * Entity mapped to table CONTACTO.
 */
public class Contacto implements Serializable {

    private Long contactoId;
    /** Not-null value. */
    private String Nombre;
    private String CorreoElectronico;
    private String Telefono;
    private String Direccion;
    private String imagenUri;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Contacto() {
    }

    public Contacto(Long contactoId) {
        this.contactoId = contactoId;
    }

    public Contacto(Long contactoId, String Nombre, String CorreoElectronico, String Telefono, String Direccion, String imagenUri) {
        this.contactoId = contactoId;
        this.Nombre = Nombre;
        this.CorreoElectronico = CorreoElectronico;
        this.Telefono = Telefono;
        this.Direccion = Direccion;
        this.imagenUri = imagenUri;
    }

    public Long getContactoId() {
        return contactoId;
    }

    public void setContactoId(Long contactoId) {
        this.contactoId = contactoId;
    }

    /** Not-null value. */
    public String getNombre() {
        return Nombre;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombre(String Nombre) {
        this.Nombre = Nombre;
    }

    public String getCorreoElectronico() {
        return CorreoElectronico;
    }

    public void setCorreoElectronico(String CorreoElectronico) {
        this.CorreoElectronico = CorreoElectronico;
    }

    public String getTelefono() {
        return Telefono;
    }

    public void setTelefono(String Telefono) {
        this.Telefono = Telefono;
    }

    public String getDireccion() {
        return Direccion;
    }

    public void setDireccion(String Direccion) {
        this.Direccion = Direccion;
    }

    public String getImagenUri() {
        return imagenUri;
    }

    public void setImagenUri(String imagenUri) {
        this.imagenUri = imagenUri;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Contacto contacto = (Contacto) o;

        if (contactoId != null ? !contactoId.equals(contacto.contactoId) : contacto.contactoId != null)
            return false;
        if (!Nombre.equals(contacto.Nombre)) return false;
        if (CorreoElectronico != null ? !CorreoElectronico.equals(contacto.CorreoElectronico) : contacto.CorreoElectronico != null)
            return false;
        if (Telefono != null ? !Telefono.equals(contacto.Telefono) : contacto.Telefono != null)
            return false;
        return !(imagenUri != null ? !imagenUri.equals(contacto.imagenUri) : contacto.imagenUri != null);

    }

    @Override
    public int hashCode() {
        int result = contactoId != null ? contactoId.hashCode() : 0;
        result = 31 * result + Nombre.hashCode();
        result = 31 * result + (CorreoElectronico != null ? CorreoElectronico.hashCode() : 0);
        result = 31 * result + (Telefono != null ? Telefono.hashCode() : 0);
        result = 31 * result + (imagenUri != null ? imagenUri.hashCode() : 0);
        return result;
    }
    // KEEP METHODS END

}
